language: php

php:
  - 7.1
  - 7.2

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - ./artisan key:generate

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls