language: php

php:
  - 7.1
  - 7.2

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - mysql -u root -e "create database mailfunnel_test"
  - ./artisan key:generate

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls