version: '2'

services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=mailfunnel
#    ports:
#      - 3306:3306

  web:
    build: .
    command: php -S 0.0.0.0:8000 -t /home/mailfunnel/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=mailfunnel
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
    ports:
      - 8080:8000
    links:
      - db
    volumes:
      - .:/home/mailfunnel/html/
