version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mailfunnel
      - MYSQL_PASSWORD=mailfunnel
      - MYSQL_DATABASE=mailfunnel
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d

  web:
    build: .
    command: php /home/mailfunnel/html/artisan serve --host=0.0.0.0
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
    ports:
      - 8000:8000
    links:
      - db
    volumes:
      - .:/home/mailfunnel/html/
